### ISSUE TITLE
Non-existing sparse frames in Extraction

### ISSUE THREAD

**Issue by Jay-IPL** [epic-kitchens/VISOR-FrameExtraction#3]
For example,

video : P03_14
In P03_14_interpolations.json, for the first sequence, "interpolation_start_frame": "P03_14_frame_0000000152.png", "interpolation_end_frame": "P03_14_frame_0000000210.png". 

However there is no these two frames in the downloaded folder 'GroundTruth-SparseAnnotations/rgb_frames/val/P03/P03_14'.

for many other sequences in P03_14, they have the same issue.

solution: I guess I should skip copying these nonexisting frames from sparse rgb folder to my output dense folder. Do you think it's acceptable?

**Comment by AhmadDarKhalil** [comment]
Thank you for mentioning the issue,
The problem comes because of a system copying problem of the sparse annotations, so the start and end frames should be "P03_14_frame_0000000151.png" and " P03_14_frame_0000000211.png" respectively but they're not currently part of the JSON object (but they have RGB images in the sparse dataset).
We'll fix that issue by giving a correction script to update this video's start and end frames and adding the missing sparse frames. This will be available in this repo within few days.

**Comment by AhmadDarKhalil** [comment]
The issue was fixed by providing a correction script "correct_interpolations.py", please read the instructions in the repository for more information on how to use the script to get the data clean and ready to use.
Thanks a lot for being patient and we really hope you'll enjoy using VISOR!
