### ISSUE TITLE
Frame mapping for interpolated frames

### ISSUE THREAD

**Issue by leobxpan** [epic-kitchens/VISOR-FrameExtraction#9]
Hi, thanks for providing the great dataset and tools. Since the `frame_mapping.json` only provides mapping from sparse frames to the originally released frames, I'm wondering how can I get the mapping for the dense frames? Or should I follow the dense frame extraction procedure?

**Comment by malcolmBurdorf** [comment]
Just a question for clarification.  If we want to use the interpolated dense masks, we need to extract dense frames and then reconstitute new videos with those frames, correct?  It's not immediately obvious how to integrate the dense frames into the full video, as if we can only use the dense frames stripped from the context of the full video.

**Comment by dimadamen** [comment]
I am not sure what you mean by "reconstitute new videos"? I am afraid I don't understand your question. Eventually a video is a set of frames, and this is what you usually put into models, so you don't need to ffmpeg those back into a video unless you're asking for visualization. We offer complete code for frame extraction (check repo in full)

**Comment by malcolmBurdorf** [comment]
Thank you for the answer!  Sorry if this is an obvious point, but I'm attempting to extract all frames of the video including dense frames, so that not just the dense frames are available to train on.  In other words, I want to train on both frames which do and do not have a mask.  It sounds like I can use this repo to extract dense frames and then extract non-dense frames separately.
